### ISSUE TITLE
add Vincent Tournier

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfb-bengalded-epigraphy#1]
@ajaniak : could you please give @tourniervincent full rights to this repository? thanks.

**Comment by ajaniak** [comment]
@tourniervincent already has right on this repository as member as tfb. But I can reduced the write access to only the 2 of you, if necessary.

**Comment by arlogriffiths** [comment]
thanks. please maintain tourniervincent’s write access.

how else has such access? if I’m not forgetting anyone, we want the following people to be able to modify the files in this repo

- Annette
- Manu
- Daniel
- Rajat
- Ryosuke
- me

best,

Arlo

Le 21 sept. 2020 à 10:24, ajaniak <notifications@github.com<mailto:notifications@github.com>> a écrit :



@tourniervincent<https://github.com/tourniervincent> already has right on this repository as member as tfb. But I can reduced the write access to only the 2 of you, if necessary.

**Comment by ajaniak** [comment]
I don't have any github account for Rajat, so I can't add him.

**Comment by arlogriffiths** [comment]
Thanks. I rather doubt Rajat will ever become an active encoder, so let's do without him for now. Closing this issue.
